# Generated by Django 4.2.2 on 2023-10-18 20:52

from django.db import migrations, models
import django.db.models.deletion
import question.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('questionNumber', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('ipFormate', tinymce.models.HTMLField()),
                ('opFormate', tinymce.models.HTMLField()),
                ('constraints', tinymce.models.HTMLField(blank=True, null=True)),
                ('inputOutputBlock', tinymce.models.HTMLField(null=True)),
                ('sampleIp', models.TextField(blank=True, null=True)),
                ('sampleOp', models.TextField(blank=True, null=True)),
                ('difficultyLevel', models.IntegerField(default=0)),
                ('maxPoints', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('timeLimit', models.IntegerField(default=1)),
                ('memoryLimit', models.IntegerField(default=524288)),
                ('accuracy', models.IntegerField(default=0)),
                ('totalSubmissions', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('junior', 'junior'), ('senior', 'senior'), ('both', 'both')], max_length=10, null=True)),
                ('expose', models.BooleanField(default=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseNumber', models.IntegerField()),
                ('inputFile', models.FileField(blank=True, upload_to=question.models.getIpPath, verbose_name='Testcase Input')),
                ('outputFile', models.FileField(blank=True, upload_to=question.models.getOpPath, verbose_name='Testcase Output')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
