# Generated by Django 4.2.2 on 2023-10-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerId', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('upTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contestId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField(blank=True)),
                ('endTime', models.DateTimeField(blank=True)),
                ('isStarted', models.BooleanField(default=False)),
            ],
        ),
    ]
