# Generated by Django 4.2.2 on 2023-10-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_questionnumber'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c')], max_length=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
